FROM docker.io/alpine:3.22.0

RUN apk add --no-cache \
     procps \
     curl \
     jq \
     && curl -o /usr/local/bin/yq -L 'https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64' \
     && chmod +x /usr/local/bin/yq \
     && curl -L "https://dl.k8s.io/release/v1.30.11/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl \
     && chmod +x /usr/local/bin/kubectl
